name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'user-srv'

jwt:
  key: 'YcaSX0JScptmSWL9'

sms:
  key: 'aaa'
  secrect: 'aaa'

redis:
  host: '127.0.0.1'
  port: 6379
  expire: 300

consul:
  host: '127.0.0.1'
  port: 8500